name: Build and Deploy Baller Stats
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    env:
        PUBLIC_URL: ${{ secrets.PUBLIC_URL }}
        REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "💡 The ${{ github.repository }} repository has been cloned."
      - name: Build bundle files
        run: |
          npm ci
          npm run build
      - name: Copy file via ssh
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: "dist/index.html,dist/static"
          target: "/sites/ballerstats.com/files/stats"
          overwrite: true
          strip_components: 1
